name: chat-app
services:
  mongo:
    image: mongo:7.0.12
    volumes:
      - mongo_data:/data/db
    networks:
      - chat-app
  api:
    # build:
    #   context: ./api
    #   target: production
    image: troyodia/chat-app-api:version1.0
    container_name: chat-app-api
    restart: unless-stopped
    env_file: ./api/.env
    networks:
      - chat-app
    depends_on:
      - mongo

  client:
    # build:
    #   context: ./client
    #   target: production
    image: troyodia/chat-app-client:version1.0
    container_name: chat-app-client
    restart: unless-stopped
    env_file: ./client/.env
    environment:
      - WDS_SOCKET_PORT=0
    networks:
      - chat-app
    depends_on:
      - api

  caddy:
    # build:
    #   context: ./caddy
    #   dockerfile: Dockerfile
    image: troyodia/chat-app-caddy:version1.0
    ports:
      - 80:80
      - 443:443
    env_file: ./.env
    # environment:
    #   DOMAIN_NAME: ${DOMAIN_NAME}
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - chat-app
    depends_on:
      - api
      - client
volumes:
  mongo_data:
  caddy_data:
  caddy_config:

networks:
  chat-app:
    driver: bridge
